server:
  port: 8090
  servlet:
    context-path: /api
logging:
  path: /var/logs
  file: parking-backend.log
  level:
    root: WARN
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://rm-wz9dhxg87delowam5jo.mysql.rds.aliyuncs.com/prod
    username: root
    password: PARKINGSMART_PSW
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update