server:
  port: 8080
  servlet:
    context-path: /api
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost/parkingsmart-backend
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update


